"""hermetic_land — in-spec lockfile regeneration gated by the hermetic determinism gate
(P3, ADR-0006). Regeneration runs INSIDE spec construction (BatchEngine._spec_for.prebuild_tree)
BEFORE the verdict, so the tree the verdict runs on is the tree that lands. If the gate is not
byte-identical-green, the land is BLOCKED (fail closed), the batch holds, and it is re-speculatable
on a later green gate.

`Regenerator` is pluggable: the real implementation materializes the tree, runs
hermetic.determinism_gate over the engine-owned lockfile, and writes the regenerated bytes back;
tests inject a fake. Only the GLOBAL lane gets a regenerator (it exclusively owns lockfile paths).
"""

from __future__ import annotations


class HermeticBlocked(Exception):
    pass


class Regenerator:
    """regen(tree) -> (tree', digest); gate_ok(tree') -> bool."""

    def regen(self, tree):
        raise NotImplementedError

    def gate_ok(self, tree) -> bool:
        raise NotImplementedError


class IdentityRegenerator(Regenerator):
    """No-op regen, always green — for lanes that own no lockfile paths."""

    def regen(self, tree):
        return tree, tree

    def gate_ok(self, tree) -> bool:
        return True


def make_prebuild(regenerator: Regenerator):
    """A prebuild_tree(tree) hook for BatchEngine._spec_for that regenerates + hermetically gates."""
    def prebuild(tree):
        tree2, digest = regenerator.regen(tree)
        if not regenerator.gate_ok(tree2):
            raise HermeticBlocked(f"hermetic gate not byte-identical-green for {tree2}")
        return tree2, digest
    return prebuild
